name: Feature request
description: Suggest an idea for this project
title: "[Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please fill out as much as you can, the more details the better we can help to implement the feature.
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: 🤔 Rationale
      description: Why do you think this feature is important and how will it benefit the project?
  - type: textarea
    id: additional
    attributes:
      label: 📋 Additional context
      description: Add any other context or information about the feature request here.